kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: fluentbit
allowPrivilegedContainer: true
allowHostNetwork: true
allowHostDirVolumePlugin: true
priority:
allowedCapabilities: []
allowHostPorts: true
allowHostPID: true
allowHostIPC: true
readOnlyRootFilesystem: false
requiredDropCapabilities: []
defaultAddCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - hostPath
  - persistentVolumeClaim
  - projected
  - secret
users:
  - system:serviceaccount:fluentbit:builder
  - system:serviceaccount:fluentbit:default
  - system:serviceaccount:fluentbit:deployer
  - system:serviceaccount:fluentbit:fluent-bit