apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  server:
    insecure: true
    route:
      enabled: true
  # dex:
  #   openShiftOAuth: true
  #   image: quay.io/ablock/dex
  #   version: openshift-connector
  # rbac:
  #   policy: |
  #      g, system:cluster-admin, role:admin
