apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: iaf-system-kafka
  namespace: network-orchestration
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      auto.create.topics.enable: "false"
      inter.broker.protocol.version: "2.8"
      log.message.format.version: "2.8"
      message.max.bytes: 369295618
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
    - name: plain
      port: 9092
      tls: false
      type: internal
    - name: tls
      port: 9093
      tls: true
      type: internal
    replicas: 3
    storage:
      type: ephemeral
    version: 2.8.0
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral