apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker2
spec:
  version: 2.8.0
  replicas: 1
  connectCluster: "my-cluster-target"
  clusters:
  - alias: "my-cluster-source"
    bootstrapServers: iaf-system-kafka-bootstrap.network-orchestration.svc.cluster.local:9092
  - alias: "my-cluster-target"
    bootstrapServers: mano-kafka-cluster-kafka-bootstrap.kafka-cluster-operator.svc.cluster.local:9092
  mirrors:
  - sourceCluster: "my-cluster-source"
    targetCluster: "my-cluster-target"    
    sourceConnector: 
      tasksMax: 3 
      config:
        replication.factor: 1 
        offset-syncs.topic.replication.factor: 1 
        sync.topic.acls.enabled: "false" 
        refresh.topics.interval.seconds: 60 
        replication.policy.separator: "" 
        replication.policy.class: "io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy" 
    heartbeatConnector: 
      config:
        heartbeats.topic.replication.factor: 1 
    checkpointConnector: 
      config:
        checkpoints.topic.replication.factor: 1 
        refresh.groups.interval.seconds: 600 
        sync.group.offsets.enabled: true 
        sync.group.offsets.interval.seconds: 60 
        emit.checkpoints.interval.seconds: 60 
        replication.policy.class: "io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy"
    topicsPattern: "tnco-state-change" 
